package glyph

import util.Rng

/**
 * The Ingress **glyph** vocabulary — the Shapers' pictographic language used in glyph hacking. Each constant is
 * one glyph; its [meanings] are the canonical English translations (the first is the [spokenName] the TTS reads
 * out). Source: the Ingress Wiki "Glyphs" translation table (active glyphs only; the retired event glyphs —
 * Call, Chase, Heart, Toast, … — are intentionally omitted).
 *
 * Pure data in `commonMain` so it's reusable + testable; consumed by the TTS "glyph" verbosity tier, which
 * announces 1–3 random glyphs by name when an agent lands a glyph hack.
 */
enum class Glyph(vararg val meanings: String) {
    ACCEPT("Accept", "Open"),
    ABANDON("Abandon"),
    ADAPT("Adapt"),
    ADVANCE("Advance"),
    AFTER("After"),
    AGAIN("Again", "Repeat"),
    ALL("All"),
    ANSWER("Answer"),
    ATTACK("Attack", "War"),
    AVOID("Avoid"),
    BALANCE("Balance", "Perfection"),
    BARRIER("Barrier"),
    BEFORE("Before"),
    BEGIN("Begin"),
    HUMAN("Human", "Being"),
    BODY("Body"),
    BREATHE("Breathe", "Live"),
    CAPTURE("Capture"),
    CHANGE("Change"),
    CHAOS("Chaos"),
    CIVILIZATION("Civilization"),
    CLEAR("Clear"),
    CLEAR_ALL("Clear All"),
    SHAPERS("Shapers", "Collective"),
    COMPLEX("Complex"),
    CONFLICT("Conflict"),
    CONSEQUENCE("Consequence"),
    CONTEMPLATE("Contemplate"),
    COURAGE("Courage"),
    CREATE("Create"),
    CREATIVITY("Creativity", "Idea", "Thought"),
    DANGER("Danger"),
    DATA("Data"),
    DEFEND("Defend"),
    DESTINATION("Destination"),
    DESTINY("Destiny"),
    DESTROY("Destroy"),
    DETERIORATE("Deteriorate"),
    DIE("Die", "Death"),
    DIFFICULT("Difficult"),
    DISCOVER("Discover"),
    DISTANCE("Distance", "Outside"),
    EASY("Easy"),
    END("End"),
    ENLIGHTENED("Enlightened", "Enlightenment"),
    EQUAL("Equal"),
    ESCAPE("Escape"),
    EVOLUTION("Evolution", "Progress", "Success"),
    FAILURE("Failure"),
    FEAR("Fear"),
    FIELD("Field"),
    FOLLOW("Follow"),
    FORGET("Forget"),
    FUTURE("Future"),
    GAIN("Gain"),
    GROW("Grow"),
    HARM("Harm"),
    HARMONY("Harmony", "Peace"),
    HAVE("Have"),
    HELP("Help"),
    HIDE("Hide"),
    ME("Me", "I"),
    IGNORE("Ignore"),
    IMPERFECT("Imperfect"),
    IMPROVE("Improve"),
    IMPURE("Impure"),
    SELF("Self", "Individual"),
    NOT("Not", "Inside"),
    INTELLIGENCE("Intelligence"),
    INTERRUPT("Interrupt"),
    JOURNEY("Journey"),
    KEY("Key"),
    KNOWLEDGE("Knowledge"),
    LEAD("Lead"),
    LEGACY("Legacy"),
    LESS("Less"),
    LIBERATE("Liberate"),
    LIE("Lie"),
    LINK("Link"),
    REINCARNATE("Reincarnate", "Live Again"),
    LOSE("Lose"),
    MESSAGE("Message"),
    MIND("Mind"),
    MORE("More"),
    MYSTERY("Mystery"),
    NATURE("Nature"),
    NEW("New"),
    NZEER("N'Zeer"),
    NEMESIS("Nemesis"),
    NOURISH("Nourish"),
    PRESENT("Present", "Now"),
    OLD("Old"),
    OPEN_ALL("Open All"),
    OSIRIS("Osiris"),
    PAST("Past"),
    PATH("Path"),
    PERSPECTIVE("Perspective"),
    PORTAL("Portal"),
    POTENTIAL("Potential"),
    PRESENCE("Presence"),
    PURE("Pure"),
    PURSUE("Pursue"),
    QUESTION("Question"),
    REACT("React"),
    REBEL("Rebel"),
    REPAIR("Repair", "Recharge"),
    RESISTANCE("Resistance", "Struggle"),
    RESTRAINT("Restraint"),
    RETREAT("Retreat"),
    SAFETY("Safety"),
    SAVE("Save"),
    SEARCH("Search"),
    SEE("See"),
    SEPARATE("Separate"),
    SHARE("Share"),
    SHIELD("Shield"),
    SIMPLE("Simple"),
    SOUL("Soul"),
    SPEED("Speed"),
    STABILITY("Stability", "Stay"),
    STAR("Star"),
    STRONG("Strong"),
    TECHNOLOGY("Technology"),
    THEM("Them"),
    TOGETHER("Together"),
    TRUTH("Truth"),
    UNBOUNDED("Unbounded"),
    WE("We", "Us"),
    USE("Use"),
    VICTORY("Victory"),
    WANT("Want"),
    WEAK("Weak"),
    WORTH("Worth"),
    XM("XM"),
    YOU("You", "Your"),
    ;

    /** The English name the TTS reads out — the first (primary) of the glyph's [meanings]. */
    val spokenName: String get() = meanings.first()

    companion object {
        /** [count] distinct random glyphs (clamped to the set size), in pick order — a glyph-hack sequence. */
        fun randomSequence(rng: Rng, count: Int): List<Glyph> {
            val pool = values().toMutableList()
            val take = count.coerceIn(0, pool.size)
            return (0 until take).map { pool.removeAt(rng.randomInt(pool.size - 1)) } // randomInt(max) is inclusive
        }
    }
}
