package system.grid

import config.Location
import config.Locations
import extension.Grid
import kotlinx.browser.document
import org.w3c.dom.HTMLAnchorElement
import org.w3c.dom.url.URL
import org.w3c.files.Blob
import org.w3c.files.BlobPropertyBag
import system.map.MapController
import system.map.ShadowGridBuilder
import system.ui.LoadingOverlay

/**
 * `?debug=capture` one-time tool: sweep every [Location] preset, build each grid, and download a
 * `PresetFixtures.kt` of raw passability snapshots ([GridFixture]). Drop the file into
 * `src/jsTest/kotlin/util/` and commit it; [util.PresetConnectivityTest] then asserts connectivity
 * offline. Re-run when presets or the tile source change materially.
 *
 * No agents/portals/3D are created — only [MapController.loadMaps], which builds the grid and (under
 * capture mode) hands the raw grid to [onGridBuilt] before carving.
 */
object GridCapture {
    private val fixtures = mutableListOf<GridFixture>()
    private var currentPreset: Location? = null

    /** Called from ShadowGridBuilder.build (capture mode) with the raw, pre-connectIslands grid. */
    fun onGridBuilt(rawGrid: Grid, w: Int, h: Int) {
        val preset = currentPreset ?: return
        fixtures.add(GridFixture.fromGrid(preset.name, rawGrid, w, h, ShadowGridBuilder.OFFSCREEN_CELL_ROWS))
    }

    fun sweep() {
        val presets = Locations.all().toList()
        fixtures.clear()
        fun next(i: Int) {
            if (i >= presets.size) {
                download()
                return
            }
            currentPreset = presets[i]
            LoadingOverlay.detail("Capturing ${presets[i].displayName} (${i + 1}/${presets.size})…")
            MapController.loadMaps(presets[i].toJSON()) { next(i + 1) }
        }
        next(0)
    }

    private fun download() {
        LoadingOverlay.detail("Captured ${fixtures.size} presets — downloading PresetFixtures.kt…")
        val body = fixtures.joinToString(",\n    ") { it.toKotlin() }
        val src = buildString {
            appendLine("package util")
            appendLine()
            appendLine("// Generated by GridCapture (?debug=capture) — raw preset passability snapshots for")
            appendLine("// offline connectivity tests. Re-generate when presets or the tile source change.")
            appendLine("val PRESET_FIXTURES = listOf(")
            appendLine("    $body,")
            append(")")
        }
        triggerDownload("PresetFixtures.kt", src)
    }

    private fun triggerDownload(filename: String, content: String) {
        val blob = Blob(arrayOf(content), BlobPropertyBag(type = "text/plain"))
        val url = URL.createObjectURL(blob)
        val anchor = document.createElement("a") as HTMLAnchorElement
        anchor.href = url
        anchor.setAttribute("download", filename)
        document.body?.appendChild(anchor)
        anchor.click()
        anchor.remove()
        URL.revokeObjectURL(url)
    }
}
