@file:Suppress("UnusedParameter")

package ai.net

// The baked champion library as bundled JSON resources under src/jsMain/resources/champions/ — ONE file per
// architecture ([requireChampion]) plus an [championIndex] manifest (arch label → filename + default + schema).
// Loaded via `require` so it is available SYNCHRONOUSLY in both webpack (browser) and Node (jsNodeTest); the
// dynamic per-file require compiles to a webpack context module over champions/*.json. Per-arch files are the
// shareable unit — a user can download/upload a single champion. The files are generated by
// scripts/bake-champs.sh — do NOT edit by hand.

/** `champions/index.json`: `{ schemaVersion, inputs, outputs, default:<label>, archs:{ <label>: <filename> } }`. */
@JsModule("./champions/index.json")
@JsNonModule
external val championIndex: dynamic

/** Require one per-arch champion file (a [GenomeIO] genome object). [file] is a manifest `archs` value. */
fun requireChampion(file: String): dynamic = js("require('./champions/' + file)")
