@file:Suppress("UnusedPrivateProperty")

package ai.net

// The baked champion library, bundled from the JSON resource (src/jsMain/resources/champions.json) via
// `require` so it is available SYNCHRONOUSLY in both webpack (browser) and Node (jsNodeTest). Shape:
// { schemaVersion, inputs, outputs, default:<label>, champions:{ <label>: <GenomeIO genome object> } }.
// Generated by scripts/bake-champs.sh — do NOT edit by hand.
@JsModule("./champions.json")
@JsNonModule
external val championsData: dynamic
