package ai.net

import kotlinx.browser.window
import system.ui.Bootstrap
import kotlin.js.Json

/**
 * The baked champion **library** (PLAN Phase 6.2 / docs/NN.md) — one pre-trained genome per [NetArch] the
 * TRAIN tab offers (two hidden layers, each width in 4/8/16/24/32 → 25 combos), so the onboarding per-arch
 * pick and a "random architecture" NN match both have a real champion to install.
 *
 * The genomes live as **one JSON file per architecture** under `src/jsMain/resources/champions/` (bundled via
 * [requireChampion], indexed by [championIndex]) — NOT hardcoded in Kotlin — so a single champion is a
 * shareable / replaceable unit: a user can download one arch's champion and someone else [installChampion]s it.
 * The dev-default files are regenerated by `scripts/bake-champs.sh`. Each genome is trained headless
 * (`ai.net.ChampionBake`) against the adaptive [ai.HeuristicPolicy] baseline. [jsonFor] falls back to the
 * default champion for any arch without one, and [Champion] delegates its default genome here.
 */
object ChampionLibrary {
    /**
     * The `champions/index.json` schema version this build understands. Bump it (and re-bake) whenever the net
     * I/O contract ([NetArch.INPUTS]/[NetArch.OUTPUTS]) or the manifest shape changes. A loaded champion is
     * validated per-genome by [GenomeIO.decode] (I/O dims), so an incompatible one is refused rather than
     * silently mis-decoded (PLAN icebox: genome/action-set versioning).
     */
    const val SCHEMA_VERSION = 1

    private const val STORE_KEY = "qgress.net.champions" // user-installed per-arch overrides (localStorage)

    // Bundled dev-default champions (arch label → genome JSON), one per file, from champions/index.json.
    private val bundled: Map<String, String> = loadBundled()

    // User-installed per-arch champions (arch label → genome JSON); persisted to localStorage, override bundled.
    private val overrides: MutableMap<String, String> = mutableMapOf()

    /** The default architecture's label — the fallback champion (`13 → 16 → 16 → 17`). */
    val DEFAULT_LABEL: String get() = championIndex["default"] as String

    private fun jsonForLabel(label: String): String? = overrides[label] ?: bundled[label]

    /** The genome JSON for [arch], or the default champion when that arch has no baked/installed champion. */
    fun jsonFor(arch: NetArch): String = jsonForLabel(arch.label()) ?: defaultJson()

    /** The default champion JSON (the `13 → 16 → 16 → 17` net). */
    fun defaultJson(): String = requireNotNull(jsonForLabel(DEFAULT_LABEL)) { "default champion $DEFAULT_LABEL missing" }

    /** The architectures with a champion (bundled or installed) — for the per-arch pick / random-arch NN matches. */
    fun bakedArchs(): List<NetArch> = (bundled.keys + overrides.keys)
        .mapNotNull { label -> runCatching { GenomeIO.decode(jsonForLabel(label) ?: return@mapNotNull null).arch }.getOrNull() }
        .distinctBy { it.label() }

    /** The held-out fitness the [arch]'s champion was tagged with (net checkpoints led vs the baseline), or null. */
    fun fitnessFor(arch: NetArch): Double? = jsonForLabel(arch.label())?.let { GenomeIO.fitnessOf(it) }

    /**
     * Install a single champion from its genome JSON, replacing that architecture's champion. Validated by
     * [GenomeIO.decode] (throws [IllegalStateException]/[IllegalArgumentException] if it isn't a genome for this
     * build's net I/O), then persisted so it survives a reload.
     */
    fun installChampion(json: String) {
        val label = GenomeIO.decode(json).arch.label() // validates the genome for this build; derives its arch
        overrides[label] = json
        persist()
    }

    /** Restore user-installed champions from `localStorage` (browser only; no-op headless). Call once at startup
     *  BEFORE the first library read (onboarding's per-arch pick). Incompatible stored champions are dropped. */
    fun restore() {
        if (Bootstrap.isNotRunningInBrowser()) return
        val saved = window.localStorage.getItem(STORE_KEY) ?: return
        runCatching {
            val obj = JSON.parse<Json>(saved)
            keysOf(obj).forEach { label -> installChampion(JSON.stringify(obj.asDynamic()[label])) }
        }.onFailure {
            console.warn("stored champions incompatible with this build — dropping them: ${it.message}")
            window.localStorage.removeItem(STORE_KEY)
        }
    }

    /** Forget all user-installed champions, reverting every arch to its bundled dev default. */
    fun resetToBundled() {
        overrides.clear()
        if (Bootstrap.isRunningInBrowser()) window.localStorage.removeItem(STORE_KEY)
    }

    /** Drop in-memory overrides without touching storage — for deterministic tests. */
    fun reset() {
        overrides.clear()
    }

    private fun persist() {
        if (Bootstrap.isNotRunningInBrowser()) return
        if (overrides.isEmpty()) {
            window.localStorage.removeItem(STORE_KEY)
            return
        }
        val obj: dynamic = js("({})")
        overrides.forEach { (label, json) -> obj[label] = JSON.parse<Json>(json) }
        window.localStorage.setItem(STORE_KEY, JSON.stringify(obj))
    }

    // Load every bundled champion via a per-file require (dynamic → a webpack context module over champions/*.json).
    private fun loadBundled(): Map<String, String> {
        validateIndex(championIndex)
        val archs = championIndex.archs
        return keysOf(archs).associateWith { label -> JSON.stringify(requireChampion(archs[label] as String)) }
    }

    private fun validateIndex(index: dynamic) {
        val v = index["schemaVersion"] as? Int
        val inputs = index["inputs"] as? Int
        val outputs = index["outputs"] as? Int
        if (v != SCHEMA_VERSION || inputs != NetArch.INPUTS || outputs != NetArch.OUTPUTS) {
            console.warn(
                "champion index schema mismatch: v=$v (want $SCHEMA_VERSION), " +
                    "io=$inputs→$outputs (want ${NetArch.INPUTS}→${NetArch.OUTPUTS})",
            )
        }
    }

    @Suppress("UnusedParameter") // `o` is referenced inside the js() intrinsic, invisible to detekt
    private fun keysOf(o: dynamic): Array<String> = js("Object.keys(o)")
}
