package ai.net

/**
 * The default baked champion (PLAN Phase 6.2) — the net the **Neural net** driver installs for the default
 * architecture ([NetArch.DEFAULT] = `13 → 16 → 16 → 17`) when nothing is saved in [NetStore]. The genome
 * itself (and one per every other baked [NetArch]) lives in the per-arch `champions/` JSON resources read by
 * [ChampionLibrary], regenerated by `scripts/bake-champs.sh` (trains each arch against the adaptive
 * [ai.HeuristicPolicy] baseline, selecting the committed genome by held-out fitness). This object stays a
 * thin alias so existing call sites keep working.
 */
object Champion {
    /** The default champion's GenomeIO JSON — the `13 → 16 → 16 → 17` net from the [ChampionLibrary]. */
    val JSON: String get() = ChampionLibrary.defaultJson()
}
