package ai.net

/**
 * The baked champion **library** (PLAN Phase 6.2 / docs/NN.md) — one pre-trained genome per [NetArch] the
 * TRAIN tab offers (two hidden layers, each width in 4/8/16/24/32 → 25 combos), so the onboarding per-arch
 * pick and a "random architecture" NN match both have a real champion to install (a net of an untrained arch
 * would play randomly). Each entry is [GenomeIO]-encoded and trained headless (`ai.net.ChampionBake`) against
 * the adaptive [ai.HeuristicPolicy] baseline. [jsonFor] falls back to the [DEFAULT_LABEL] champion for any
 * arch not in the library, and [Champion] delegates its default genome here.
 */
object ChampionLibrary {
    /** The default architecture's label ([NetArch.DEFAULT] = `13 → 16 → 16 → 17`) — the fallback champion. */
    const val DEFAULT_LABEL: String = "13 → 16 → 16 → 17"

    // arch label → GenomeIO JSON, generated by scripts/bake-champs.sh (ai.net.ChampionGenomes). Until the
    // full sweep lands only the default arch is baked; every other arch falls back to it via [jsonFor].
    private val BAKED: Map<String, String> get() = ChampionGenomes.BAKED

    /** The baked genome JSON for [arch], or the [DEFAULT_LABEL] champion when that arch isn't in the library. */
    fun jsonFor(arch: NetArch): String = BAKED[arch.label()] ?: defaultJson()

    /** The default champion JSON (the `13 → 16 → 16 → 17` net). */
    fun defaultJson(): String = BAKED.getValue(DEFAULT_LABEL)

    /** The architectures with a baked champion (for the onboarding per-arch pick / random-arch NN matches). */
    fun bakedArchs(): List<NetArch> = BAKED.keys.mapNotNull { runCatching { GenomeIO.decode(BAKED.getValue(it)).arch }.getOrNull() }
}
