#!/usr/bin/env bash
#
# Rebake one champion per net architecture and regenerate the committed genome library.
#
#   ./scripts/bake-champs.sh          # train every arch, regenerate ChampionGenomes.kt
#   ./scripts/bake-champs.sh --bench  # just time a match (size the training budget), no bake
#
# The heavy lifting lives in the reusable harness `ai.net.ChampionBake` (jsTest): it trains a net per
# NetArch (the TRAIN-tab 4/8/16/24/32 x 4/8/16/24/32 sweep) against the adaptive HeuristicPolicy baseline
# and, per arch, commits the ELITE genome with the best HELD-OUT (unseen-seed) margin — so an overfit
# champion is never shipped. Each winner is printed as `BAKEGENOME|<label>|<json>`; this script harvests
# those from the JUnit XML and rewrites src/jsMain/kotlin/ai/net/ChampionGenomes.kt. Review the diff, run
# the gate (`./gradlew ktlintCheck detekt compileKotlinJs jsNodeTest`), then commit.
#
# It's env-gated (BAKE_CHAMPS=1) so the normal test run skips it, and lifts Mocha's 60 s per-test cap via
# -PmochaTimeout for the minutes-long training runs.
#
set -euo pipefail
cd "$(dirname "$0")/.."

# Pick up the project toolchain (JDK 21) if the shell doesn't already have it.
if [ -z "${JAVA_HOME:-}" ] && [ -x /usr/lib/jvm/java-21-openjdk-amd64/bin/java ]; then
    export JAVA_HOME="/usr/lib/jvm/java-21-openjdk-amd64"
fi

GEN="src/jsMain/kotlin/ai/net/ChampionGenomes.kt"
XML_DIR="build/test-results/jsNodeTest"

if [ "${1:-}" = "--bench" ]; then
    echo "==> Timing a bake match (BAKE_BENCH)…"
    BAKE_BENCH=1 ./gradlew jsNodeTest --tests 'ai.net.ChampionBake' -PmochaTimeout=600s --console=plain --rerun
    grep -rhoE 'BAKE bench[^<]*' "$XML_DIR" 2>/dev/null || echo "(no bench output found)"
    exit 0
fi

echo "==> Baking one champion per architecture (this takes many minutes)…"
echo "    Live progress streams below: 'BAKE [n/25 arch] gen g/G …' per generation, then a per-arch DONE line."
# -PbakeVerbose streams the test's stdout live (the whole sweep is one long test), so you can watch it work.
BAKE_CHAMPS=1 ./gradlew jsNodeTest --tests 'ai.net.ChampionBake' \
    -PmochaTimeout=3600s -PbakeVerbose=1 --console=plain --rerun

echo "==> Harvesting baked genomes from the JUnit XML…"
python3 - "$XML_DIR" "$GEN" <<'PY'
import sys, os, re, glob, html

xml_dir, gen_path = sys.argv[1], sys.argv[2]
lines = []
for path in glob.glob(os.path.join(xml_dir, "*.xml")):
    with open(path, encoding="utf-8") as f:
        for raw in f:
            for m in re.finditer(r"BAKEGENOME\|[^\n<]*", html.unescape(raw)):
                lines.append(m.group(0))

entries = {}
for line in lines:
    _, label, js = line.split("|", 2)
    entries[label] = js.strip()

if not entries:
    sys.exit("ERROR: no BAKEGENOME lines found — did the bake run? (ChampionGenomes.kt left untouched)")

def kt_key(label):   # embed the arch label as an ASCII-safe Kotlin string key (U+2192 arrow -> →)
    return label.replace("→", "\\u2192")

def kt_val(js):      # embed the JSON as a Kotlin string literal (escape backslashes, then quotes)
    return js.replace("\\", "\\\\").replace('"', '\\"')

body = ",\n".join(
    '        "%s" to\n            "%s"' % (kt_key(k), kt_val(entries[k]))
    for k in entries
)
out = (
    "package ai.net\n\n"
    "// GENERATED by scripts/bake-champs.sh — do NOT edit by hand. One GenomeIO-encoded champion per baked\n"
    "// NetArch (arch label -> JSON). Regenerate with `scripts/bake-champs.sh`, review the diff, then commit.\n"
    "internal object ChampionGenomes {\n"
    "    val BAKED: Map<String, String> = mapOf(\n"
    "%s,\n"
    "    )\n"
    "}\n"
) % body
with open(gen_path, "w", encoding="utf-8") as f:
    f.write(out)
print("wrote %d champions to %s" % (len(entries), gen_path))
PY

echo
echo "==> ChampionGenomes.kt regenerated. Next:"
echo "    ./gradlew ktlintFormat && ./gradlew ktlintCheck detekt compileKotlinJs jsNodeTest"
echo "    git add -A && git commit   # after reviewing the diff"
